### ISSUE TITLE
Recommend making configurable files into templates

### ISSUE THREAD

**Issue by jason-technology** [aristanetworks/cloudvision-ztpaas-utils#7]
Since the bootstrap.py file has to be configured, it would be beneficial for some users if the file were a template.
For example:

cvAddr = "${cvAddr}"
enrollmentToken = "${enrollmentToken}"
cvproxy = "${cvproxy}"
eosUrl = "${eosUrl}"

Is pretty standard templating language.

This would even be helpful for your own teams while packaging ZTP docker images that dynamically insert the token.

As it is now, I download this file and make the changes listed above then run through templating to apply values.
providing it natively as a template would save some users a lot of work.
Those modifying it manually still have to modify it manually and it wouldn't add much for them to do.

**Comment by harshitk-arista** [comment]
Thanks for the suggestion. A jinja template has been added - https://github.com/aristanetworks/cloudvision-ztpaas-utils/blob/main/BootstrapScriptWithToken/bootstrap_template.j2

**Comment by harshitk-arista** [comment]
Closing this as the template has been added.
